element_list = [
    "Production",
    "Imports",
    "Exports",
    "Retail",
    "Seed",
    "Feed",
    "Stocks"
    ]

item_list = [
    "All products",
    "Cereals - Excluding Beer",
    "Starchy Roots",
    "Sugar Crops",
    "Sugar & Sweeteners",
    "Pulses",
    "Treenuts",
    "Oilcrops",
    "Vegetable Oils",
    "Vegetables",
    "Fruits - Excluding Wine",
    "Stimulants",
    "Spices",
    "Alcoholic Beverages",
    "Miscellaneous",
    "Meat",
    "Offals",
    "Animal fats",
    "Sugar & Sweeteners",
    "Fish, Seafood",
    "Aquatic Products, Other",
    "Vegetal Products",
    "Starchy Roots",
    "Vegetable Oils",
    "Milk - Excluding Butter",
    "Eggs",
    "Wheat and products",
    "Barley and products",
    "Maize and products",
    "Rye and products",
    "Oats",
    "Millet and products",
    "Sorghum and products",
    "Cereals, Other",
    "Potatoes and products",
    "Cassava and products",
    "Sweet potatoes",
    "Roots, Other",
    "Yams",
    "Sugar cane",
    "Sugar beet",
    "Sugar non-centrifugal",
    "Sugar (Raw Equivalent)",
    "Sweeteners, Other",
    "Beans",
    "Peas",
    "Pulses, Other and products",
    "Nuts and products",
    "Groundnuts",
    "Soyabeans",
    "Sunflower seed",
    "Rape and Mustardseed",
    "Cottonseed",
    "Coconuts - Incl Copra",
    "Sesame seed",
    "Palm kernels",
    "Olives (including preserved)",
    "Oilcrops, Other",
    "Soyabean Oil",
    "Groundnut Oil",
    "Sunflowerseed Oil",
    "Rape and Mustard Oil",
    "Cottonseed Oil",
    "Palmkernel Oil",
    "Palm Oil",
    "Coconut Oil",
    "Sesameseed Oil",
    "Olive Oil",
    "Ricebran Oil",
    "Maize Germ Oil",
    "Oilcrops Oil, Other",
    "Tomatoes and products",
    "Onions",
    "Vegetables, other",
    "Oranges, Mandarines",
    "Lemons, Limes and products",
    "Grapefruit and products",
    "Citrus, Other",
    "Bananas",
    "Plantains",
    "Apples and products",
    "Pineapples and products",
    "Dates",
    "Grapes and products (excl wine)",
    "Fruits, other",
    "Coffee and products",
    "Cocoa Beans and products",
    "Tea (including mate)",
    "Pepper",
    "Pimento",
    "Cloves",
    "Spices, Other",
    "Wine",
    "Beer",
    "Beverages, Fermented",
    "Beverages, Alcoholic",
    "Alcohol, Non-Food",
    "Infant food",
    "Bovine Meat",
    "Mutton & Goat Meat",
    "Pigmeat",
    "Poultry Meat",
    "Meat, Other",
    "Offals, Edible",
    "Fats, Animals, Raw",
    "Butter, Ghee",
    "Cream",
    "Honey",
    "Freshwater Fish",
    "Demersal Fish",
    "Pelagic Fish",
    "Marine Fish, Other",
    "Crustaceans",
    "Cephalopods",
    "Molluscs, Other",
    "Meat, Aquatic Mammals",
    "Aquatic Animals, Others",
    "Aquatic Plants",
    "Fish, Body Oil",
    "Fish, Liver Oil",
    "Rice and products",
    "Vegetal Products",
    "Cereals - Excluding Beer",
    "Starchy Roots",
    "Sugar Crops",
    "Sugar & Sweeteners",
    "Pulses",
    "Treenuts",
    "Oilcrops",
    "Vegetable Oils",
    "Vegetables",
    "Fruits - Excluding Wine",
    "Stimulants",
    "Spices",
    "Alcoholic Beverages",
    "Animal Products",
    "Meat",
    "Offals",
    "Animal fats",
    "Milk - Excluding Butter",
    "Eggs",
    "Fish, Seafood",
    "Aquatic Products, Other"
]

profile_list = [
    "Single year",
    "Continuous",
    "Gradual"
]

region_list = [
    "North",
    "South",
    "East",
    "West",
    "Scotland",
    "England",
    "Ireland",
    "Wales",
    "Overseas"
]